### PR TITLE
refactor event request parser

### PR DESCRIPTION
**Pull request by snmatsui**
We have UnknownEvent now, so events are converted to BaseEvent always.

### CODE REVIEW

**Review by moririnson — COMMENTED** [review]
Why is this refactoring needed?

**Comment by Vaduz** [comment]
If it always returns `UnknownEvent`, `testParseEventRequest` tests must be fail.
Could you tell me your environment and try to run above tests on your machines.

**Comment by snmatsui** [comment]
> Why is this refactoring needed?

My goal is getting actual event class from event json from `BaseEvent@getEvent`.
https://github.com/line/line-bot-sdk-php/pull/344

We should stop parsing not-signature-validated json using such methods of course, this method is useful for 
 storing received event data or debugging.

**Comment by snmatsui** [comment]
> If it always returns `UnknownEvent`, `testParseEventRequest` tests must be fail.
> Could you tell me your environment and try to run above tests on your machines.

[environment]
WSL2 Ubuntu 20.04
php 7.4.15

[test result]
```
$ php ./vendor/phpunit/phpunit/phpunit ./tests/
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

..................nohup: redirecting stderr to stdout
.............................................  63 / 142 ( 44%)
............................................................... 126 / 142 ( 88%)
................                                                142 / 142 (100%)

Time: 7.37 seconds, Memory: 16.00 MB

OK (142 tests, 1488 assertions)
```

**Comment by snmatsui** [comment]
> If it always returns `UnknownEvent`, `testParseEventRequest` tests must be fail.

I understand any event data (`events` in received json or `$parsedReq['events']`) are always converted one instance of `BaseEvent` by `parseEventRequest` if the signature is correct.
This behavior is not changed before my PR and after my PR.
`testParseEventRequest` tests all 35 events are converted one instance of `BaseEvent` using `assertInstanceOf`.

**Comment by moririnson** [comment]
@snmatsui Sorry to late for review.
`UnknownEvent` extends `BaseEvent`. So I think you can call `UnknownEvent@getEvent`. 
https://github.com/line/line-bot-sdk-php/blob/210d87af3f5fa3ed7837c3c875e39e1e3caeb9b7/src/LINEBot/Event/UnknownEvent.php#L28
I'll close this p-r because I couldn't understand it why is needed.
Please reopen it if you can explain detail purpose（why is needed & Why can't we debug the case at the current codes?） for it.

**Pull request closed without merging**
