### PR TITLE
support for longer text message

### PR DESCRIPTION
**Pull request by manandhar**
the template message are always capped to 60.

### CODE REVIEW

**Comment by tokuhirom** [comment]
I could not understand what kind of problems were solved with this patch.

**Comment by manandhar** [comment]
the message are always capped to 60.

text limit for button template is
Max: 160 characters (no image or title)
Max: 60 characters (message with an image or title)

and since the template always included the `thumbnailImageUrl` and `title` the The Max limit for text is capped

**Comment by tokuhirom** [comment]
If the value of text, thumbnailImage is null, the API server limits the number of characters in text to 160.

**Comment by manandhar** [comment]
Thanks a lot.

**Pull request closed without merging**
