### PR TITLE
add getMessageType

### PR DESCRIPTION
**Pull request by tamucola**
add getMessageType

### CODE REVIEW

**Comment by moznion** [comment]
Thank you for sending pull request.
Could you solve the following issues?

1. Please write test code (rel: https://github.com/line/line-bot-sdk-php/blob/master/tests/LINEBot/EventRequestParserTest.php)
2. Please sign ICLA (https://feedback.line.me/enquete/public/919-h9Yqmr1u)

**Comment by tamucola** [comment]
oh...  I'm not good at English....

**Comment by Vaduz** [comment]
Let me know when you signed ICLA, then we can merge your pull request.  Thank you.

**Comment by moznion** [comment]
@tamucola ping

**Comment by tamucola** [comment]
@moznion @Vaduz 
I signed ICLA!111

**Comment by moznion** [comment]
Thank you so much :beer:

**Pull request merged**
