### PR TITLE
Cleanup development environments

### PR DESCRIPTION
**Pull request by Vaduz**
Clean up `Makefile` and some stuff moved to `composer.json`.
And I revised phpmd rules.
See also: #127

### CODE REVIEW

**Comment by lintangtimur** [comment]
when i experiment to test your code and run it(im change the code same as your CURLHttpClientTest), it generates some error.

in this section code
```php
nohup %s:%d %s > /dev/null & echo $!
``` 
its produces `The system cannot find the path specified.`
then from `> /dev/null` to `> nul`, result is
`nohup: ignoring input and redirecting stderr to stdout`

thanks. sry for my bad

**Comment by Vaduz** [comment]
The test can not run on Windows environment because we are using platform specific commands as you mentioned.

**Comment by lintangtimur** [comment]
oh okay, thank you

**Comment by Vaduz** [comment]
@lintangtimur I pushed work around codes for Windows. Please check.

**Pull request merged**
