### PR TITLE
Add API for RichMenu Control

### PR DESCRIPTION
**Pull request by kiwi-26**
Issue #114
Add API for RichMenu Control (Link, Unlink, Create, List, Delete).
Richmenu image upload function is not implemented.

### CODE REVIEW

**Comment by Vaduz** [comment]
Thank you for your contribution!  I already have same feature branch, but image upload feature is not well confirmed well. Reason why I don't make it pull-request here is it is hard to implement to satisfy PHP 5.4. You can check the diff here: https://github.com/Vaduz/line-bot-sdk-php/pull/1/files
To close the issue #114, It is necessary to have image upload feature. I appreciate that you reference my implementation, then I can merge to master.

**Comment by kiwi-26** [comment]
Thank you for your comment! I couldn't implement image upload feature by same reason.
One solution is to change requirement and terminate the support of PHP 5.4.
Are there any reasons to continue supporting old version?

**Comment by Vaduz** [comment]
There is the reason when I was implementing it but I can't remember. It make sense to me discontinue to support PHP 5.4 by now.

**Comment by kiwi-26** [comment]
I implemented image upload function.
I also referenced PR suggested above, and fixed interfaces of some methods.
I apologize for many commits due to lack of tests.

**Comment by Vaduz** [comment]
@kiwi-26 Have you signed CCLA?

**Comment by kiwi-26** [comment]
I am sorry for ignorance, but what is CCLA?

**Comment by Vaduz** [comment]
@kiwi-26 Check out this document.
https://github.com/line/line-bot-sdk-php/blob/master/CONTRIBUTING.md

**Pull request merged**
