### PR TITLE
Trim heading whitespaces which are on response header value

### PR DESCRIPTION
**Pull request by moznion**
## now

```
'Content-Type' => ' application/json;charset=UTF-8'
```

## tobe

```
'Content-Type' => 'application/json;charset=UTF-8',
```

### CODE REVIEW

**Comment by Vaduz** [comment]
Have you checked `http_parse_headers`?
http://php.net/manual/pl/function.http-parse-headers.php

**Comment by moznion** [comment]
It looks cool, however unfortunately that function depends on PECL http module.
I think we should not increase dependencies of this SDK.

How do you feel?

**Comment by Vaduz** [comment]
Agreed. Ignore my previous comment.

**Comment by moznion** [comment]
Thanks!

**Pull request merged**
